[[redirects]]
  from = "/bio_search/*"
  to = "https://anybio-d5752deb0c4d.herokuapp.com/bio_search/:splat"
  status = 200
[[redirects]]
  from = "/.well-known/*"
  to = "https://anybio-d5752deb0c4d.herokuapp.com/.well-known/:splat"
  status = 200

[[headers]]
  for = "/*.yaml"
  [headers.values]
    Content-Type = "text/yaml"
